# Generated by Django 2.2.4 on 2019-09-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures')),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'agent')], default='buyer', max_length=10)),
                ('user_bio', models.TextField(max_length=500, null=True)),
                ('contact_number', models.IntegerField(default=0, null=True)),
                ('facebook_link', models.CharField(max_length=200, null=True)),
                ('instagram_link', models.CharField(max_length=200, null=True)),
                ('twitter_link', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
